### ISSUE TITLE
lost EncodeCaller

### ISSUE THREAD

**Issue by getk032** [thessem/zap-prettyconsole#4]
import (
	prettyconsole "github.com/thessem/zap-prettyconsole"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"time"
)

func main() {
	// Instead of zap.NewDevelopment()
	// without caller
	// fixme it doesn't work for EncodeCaller
	logger := prettyconsole.NewLogger(zapcore.Level(zap.DebugLevel))

	// fixme it's work
	// logger, _ = zap.NewDevelopment()

	// I normally use the un-sugared logger. I like the type-safety.
	// You can use logger.Sugar() if you prefer though!
	logger.Info("doesn't this look nice",
		zap.Complex64("nice_level", 12i-14),
		zap.Time("the_time", time.Now()),
		zap.Bools("nice_enough", []bool{true, false}),
		zap.Namespace("an_object"),
		zap.String("field_1", "value_1"),
		zap.String("field_2", "value_2"),
	)

	testcaller.LogLine(logger)

	logger.Sync()
}

// github.com/thessem/zap-prettyconsole v0.4.0
// go.uber.org/zap v1.27.0

**Comment by getk032** [comment]
output: 
1. zap.NewDevelopment(): 
```json 
2024-05-04T17:09:35.597+0800    INFO    zap2/main.go:22 doesn't this look nice  {"nice_level": "-14+12i", "the_time": "2024-05-04T17:09:35.597+0800", "nice_enough": [true, false], "an_object": {"field_1": "value_1", "field_2": "value_2"}}
```
2. prettyconsole.NewLogger(zapcore.Level(zap.DebugLevel))
```json
5:11PM INF > doesn't this look nice nice_level=-14+12i the_time=2024-05-04T17:11:08+08:00
  ↳ nice_enough=[true, false]
  ↳ an_object.field_1=value_1 .field_2=value_2
```
without attribute zap2/main.go:22

**Comment by thessem** [comment]
The default setting for prettyconsole is to omit the caller field, since I personally find when I am developing I've already got a very good idea of where log lines are emitted from (see https://github.com/thessem/zap-prettyconsole/blob/main/encoder.go#L47). If you look in [the examples](https://github.com/thessem/zap-prettyconsole/blob/main/internal/readme/example_test.go#L100) you'll find a snippet to turn it back on.

Zap's configuration API for encoders isn't extremely ergonomic but I'm hoping that'll work for your use-case.

**Comment by getk032** [comment]
thank you, it's work.
